name: Build with GCC and Clang

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux-gcc:
    name: Linux (GCC)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y build-essential
      - run: |
          mkdir build && cd build
          cmake .. -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++
          cmake --build . --parallel

  linux-clang:
    name: Linux (Clang)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y clang
      - run: |
          mkdir build && cd build
          cmake .. -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
          cmake --build . --parallel

  windows-gcc:
    name: Windows (GCC via MinGW)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake make
      - shell: msys2 {0}
        run: |
          mkdir build && cd build
          cmake .. -G "MinGW Makefiles" -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++
          cmake --build .

  windows-clang:
    name: Windows (Clang)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "17"
      - run: |
          mkdir build && cd build
          cmake .. -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
          cmake --build . --parallel
