name: CMake Build Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BUILD_TYPE: Release

jobs:
  cmake-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build all components
        run: |
          components=(
            formatter_lib
            formatter_ex_lib
            solver_lib
            hello_world_application
            solver_application
          )

          for dir in "${components[@]}"; do
            echo "Building $dir..."
            mkdir -p "$dir/build"
            pushd "$dir/build"
            cmake .. -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
            cmake --build . --config ${{ env.BUILD_TYPE }}
            popd
          done
